language: java

jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7

install:
  - ./gradlew -PossrhUsername=none -PossrhPassword=none jars

script:
  - ./gradlew -PossrhUsername=none -PossrhPassword=none --info --stacktrace check
